name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Trigger deployment on the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade huggingface_hub

    - name: Hugging Face Spaces Deploy
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}  # Token stored in GitHub Secrets
      run: |
        git config --global user.email "chinonsoodiaka@gmail.com"
        git config --global user.name "Blaqadonis"
        echo "Logging in to Hugging Face"
        huggingface-cli login --token $HF_TOKEN
        echo "Setting up git remote"
        git remote remove hf || true
        git remote add hf https://Blaqadonis:$HF_TOKEN@huggingface.co/spaces/Blaqadonis/Blaqs-PDF-Chatbot
        echo "Disabling Git LFS"
        git lfs uninstall
        echo "Pushing to Hugging Face Spaces"
        git push hf main --force || (echo "Push failed. Error:" && git push hf main --force -v)

    - name: Verify Deployment
      run: |
        echo "Deployment attempt completed. Please check https://huggingface.co/spaces/Blaqadonis/Blaqs-PDF-Chatbot to verify."