name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Trigger deployment on the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade huggingface_hub

    - name: Hugging Face Spaces Deploy
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}  # Token stored in GitHub Secrets
      run: |
        git config --global user.email "chinonsoodiaka@gmail.com"
        git config --global user.name "Blaqadonis"
        huggingface-cli login --token $HF_TOKEN --add-to-git-credential
        git remote add hf https://huggingface.co/spaces/Blaqadonis/Blaqs-PDF-Chatbot.git
        git push hf main || (echo "Push failed. Error:" && cat /tmp/git_push_error.log)

    - name: Verify Deployment
      run: |
        echo "Deployment pushed to Hugging Face Spaces. Please check https://huggingface.co/spaces/Blaqadonis/Blaqs-PDF-Chatbot to verify."